---
title: "Lab5 Task 2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Task 2

```{r, include=FALSE}
# Needed packages
required_packages <- c("igraph","rstudioapi","knitr")
for (pac in required_packages) {
  if(!require(pac,  character.only=TRUE)){
    install.packages(pac, repos="http://cran.rstudio.com")
    library(pac,  character.only=TRUE)
  } 
}
rm(pac)
rm(required_packages)

# Needed data
g = as.undirected(read.graph("./data/wikipedia.gml", format="gml"))

# Functions
detect.and.plot = function (comm.detector) {
  community = comm.detector(g)
  #print(membebrship(community))
  plot(community,g)
  return(modularity(community))
}

## Functions for sample a graph
sample.vertices = function (g, perc) {
  n_vertices = round(length(V(g))*perc)
  sampled_vertices = sample(V(g), n_vertices)
  return(induced_subgraph(g, sampled_vertices))
}

sample.edges = function (g, perc) {
  n_edges = round(length(E(g))*perc)
  sampled_edges = sample(E(g), n_edges)
  return(subgraph.edges(g, sampled_edges))
}

```



```{r}
for (i in seq(0.25, 0.325, 0.025)) {
  sampled_g = sample.vertices(as.undirected(g), i)
  n_vertices = length(V(sampled_g))
  
  #detect.and.plot(edge.betweenness.community) TOO MUCH TIME
  #detect.and.plot(fastgreedy.community) UNDIRECTED
  #detect.and.plot(label.propagation.community)
  start_time <- Sys.time()
  community = edge.betweenness.community(sampled_g)
  end_time <- Sys.time()
  #print(membebrship(community))
  #plot(community, sampled_g) 
  #data = rbind(data, data.frame(p=i, size=n_vertices, time=(end_time - start_time)))
  data = rbind(data, data.frame(p=i, size=n_vertices, time=(end_time - start_time), mod=modularity(community)))
}
data
```

## Sample the graph
```{r}
test.algorithm = function (func, g) {
  start_time <- Sys.time()
  community = func(g)
  end_time <- Sys.time()
  return(data.frame(id=algorithm(community), time=(end_time-start_time), mod=modularity(community)))
}
data = data.frame(id=character(), time=numeric(), mod=numeric())
#rbind(data, test.algorithm(edge.betweenness,sample.vertices(g, 0.3)))
data = rbind(data, test.algorithm(fastgreedy.community,g))
data = rbind(data, test.algorithm(label.propagation.community,g))
data = rbind(data, test.algorithm(leading.eigenvector.community,g))
data = rbind(data, test.algorithm(multilevel.community,g))
#data = rbind(data, test.algorithm(optimal.community,g))
#data = rbind(data, test.algorithm(spinglass.community,g))
data = rbind(data, test.algorithm(walktrap.community,g))
data
```